apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:


- path: src 
  contents:

  # validates checksums automatically from release notes

  - path: github.com/k3s-io/k3s
    githubRelease:
      slug: k3s-io/k3s
      tag: v1.24.16+k3s1 
      disableAutoChecksumValidation: true 
    includePaths:
    - "k3s"
    - "k3s-airgap-images-amd64.tar"


  - path: github.com/derailed/k9s
    githubRelease:
      slug: derailed/k9s
      tag: v0.27.4
      disableAutoChecksumValidation: true 
    includePaths:
    - "k9s_Linux_amd64.tar.gz"


  - path: github.com/containerd/nerdctl
    githubRelease:
      slug: containerd/nerdctl
      tag: v1.5.0
      disableAutoChecksumValidation: true
    includePaths:
    - "nerdctl-1.3.1-linux-amd64.tar.gz"

